# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 2
# Label requiring a response
responseRequiredLabel: answered
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  This issue has been automatically closed because it was marked as "answered", and there wasn't any recent activity on this issue.