// // Copyright 2024 The Flutter Workmanager Authors. All rights reserved.
// // Use of this source code is governed by a MIT-style license that can be
// // found in the LICENSE file.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.fluttercommunity.workmanager.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object WorkmanagerApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Task status for debugging and monitoring. */
enum class TaskStatus(val raw: Int) {
  /** Task has been scheduled */
  SCHEDULED(0),
  /** Task has started execution */
  STARTED(1),
  /** Task completed successfully */
  COMPLETED(2),
  /** Task failed */
  FAILED(3),
  /** Task was cancelled */
  CANCELLED(4),
  /** Task is being retried */
  RETRYING(5),
  /** Task was rescheduled for later execution */
  RESCHEDULED(6);

  companion object {
    fun ofRaw(raw: Int): TaskStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * An enumeration of various network types that can be used as Constraints for work.
 *
 * Fully supported on Android.
 *
 * On iOS, this enumeration is used to define whether a piece of work requires
 * internet connectivity, by checking for either [NetworkType.connected] or
 * [NetworkType.metered].
 */
enum class NetworkType(val raw: Int) {
  /** Any working network connection is required for this work. */
  CONNECTED(0),
  /** A metered network connection is required for this work. */
  METERED(1),
  /** Default value. A network is not required for this work. */
  NOT_REQUIRED(2),
  /** A non-roaming network connection is required for this work. */
  NOT_ROAMING(3),
  /** An unmetered network connection is required for this work. */
  UNMETERED(4),
  /**
   * A temporarily unmetered Network. This capability will be set for
   * networks that are generally metered, but are currently unmetered.
   *
   * Android API 30+
   */
  TEMPORARILY_UNMETERED(5);

  companion object {
    fun ofRaw(raw: Int): NetworkType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * An enumeration of backoff policies when retrying work.
 * These policies are used when you have a return ListenableWorker.Result.retry() from a worker to determine the correct backoff time.
 * Backoff policies are set in WorkRequest.Builder.setBackoffCriteria(BackoffPolicy, long, TimeUnit) or one of its variants.
 */
enum class BackoffPolicy(val raw: Int) {
  /** Used to indicate that WorkManager should increase the backoff time exponentially */
  EXPONENTIAL(0),
  /** Used to indicate that WorkManager should increase the backoff time linearly */
  LINEAR(1);

  companion object {
    fun ofRaw(raw: Int): BackoffPolicy? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * An enumeration of the conflict resolution policies when registering one-off work with the same unique name.
 *
 * This policy determines what happens when you register a one-off task with a unique name that already exists.
 *
 * See: https://developer.android.com/reference/androidx/work/ExistingWorkPolicy
 */
enum class ExistingWorkPolicy(val raw: Int) {
  /** If there is existing pending (uncompleted) work with the same unique name, append the newly-specified work as a child of all the leaves of that work sequence. */
  APPEND(0),
  /**
   * If there is existing pending (uncompleted) work with the same unique name, do nothing.
   * The new work request is ignored and the existing work continues unchanged.
   */
  KEEP(1),
  /**
   * If there is existing pending (uncompleted) work with the same unique name, cancel and delete it.
   * The new work request replaces the existing one entirely.
   */
  REPLACE(2),
  /**
   * If there is existing pending (uncompleted) work with the same unique name, it will be updated with the new specification.
   * Note: This maps to appendOrReplace in the native implementation.
   */
  UPDATE(3);

  companion object {
    fun ofRaw(raw: Int): ExistingWorkPolicy? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * An enumeration of the conflict resolution policies when registering periodic work with the same unique name.
 *
 * This policy determines what happens when you register a periodic task with a unique name that already exists.
 * This is especially important during development when you might register the same task multiple times
 * with different frequencies or configurations.
 *
 * See: https://developer.android.com/reference/androidx/work/ExistingPeriodicWorkPolicy
 */
enum class ExistingPeriodicWorkPolicy(val raw: Int) {
  /**
   * If there is existing pending (uncompleted) work with the same unique name, do nothing.
   * The new work request is ignored and the existing work continues unchanged.
   *
   * **Warning**: If you previously registered a periodic task with a short frequency
   * (e.g., 15 minutes) and later register the same task with a longer frequency (e.g., 2 hours),
   * the task will continue running at the original short frequency. This can cause confusion
   * during development. Consider using [update] instead.
   */
  KEEP(0),
  /**
   * If there is existing pending (uncompleted) work with the same unique name, cancel and delete it.
   * The new work request replaces the existing one entirely.
   *
   * **Deprecated**: Android recommends using [update] instead for less disruptive updates.
   */
  REPLACE(1),
  /**
   * If there is existing pending (uncompleted) work with the same unique name, it will be updated with the new specification.
   *
   * **Recommended** - updates existing work without canceling running workers and preserves original timing.
   * This is the default policy for periodic tasks to prevent frequency confusion.
   *
   * Available since WorkManager 2.8.0.
   */
  UPDATE(2);

  companion object {
    fun ofRaw(raw: Int): ExistingPeriodicWorkPolicy? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * An enumeration of policies that help determine out of quota behavior for expedited jobs.
 *
 * Only supported on Android.
 */
enum class OutOfQuotaPolicy(val raw: Int) {
  /**
   * When the app does not have any expedited job quota, the expedited work request will
   * fallback to a regular work request.
   */
  RUN_AS_NON_EXPEDITED_WORK_REQUEST(0),
  /**
   * When the app does not have any expedited job quota, the expedited work request will
   * we dropped and no work requests are enqueued.
   */
  DROP_WORK_REQUEST(1);

  companion object {
    fun ofRaw(raw: Int): OutOfQuotaPolicy? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Foreground service types supported for Android long-running workers.
 *
 * These map to the foreground service types introduced by Android 14
 * (API level 34), when specifying a type became mandatory for apps targeting
 * SDK 34+. See:
 * https://developer.android.com/about/versions/14/changes/fgs-types-required
 */
enum class ForegroundServiceType(val raw: Int) {
  /**
   * Used for long-running data synchronization, uploads and downloads that
   * are important to the user.
   */
  DATA_SYNC(0),
  /**
   * Used for short, critical work that the user is aware of and that must
   * complete quickly (a few minutes at most).
   */
  SHORT_SERVICE(1);

  companion object {
    fun ofRaw(raw: Int): ForegroundServiceType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Android-only configuration that promotes a worker to a foreground service
 * while it runs, keeping the process alive for long-running work.
 *
 * When provided to [OneOffTaskRequest.foregroundServiceConfig] or
 * [PeriodicTaskRequest.foregroundServiceConfig], the worker calls
 * WorkManager's `setForegroundAsync` as soon as it starts and shows a
 * notification for the whole duration of the task.
 *
 * All fields are optional; the platform implementation fills in sane
 * defaults for anything that is not provided.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ForegroundServiceConfig (
  /** Title shown in the foreground service notification. */
  val notificationTitle: String? = null,
  /** Body text shown in the foreground service notification. */
  val notificationText: String? = null,
  /**
   * Id of the notification channel used for the foreground service
   * notification (Android 8.0+).
   */
  val notificationChannelId: String? = null,
  /** User-visible name of the notification channel. */
  val notificationChannelName: String? = null,
  /** Id used for the foreground service notification. */
  val notificationId: Long? = null,
  /**
   * Foreground service type to start with (Android 14+). Defaults to
   * [ForegroundServiceType.dataSync].
   */
  val foregroundServiceType: ForegroundServiceType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ForegroundServiceConfig {
      val notificationTitle = pigeonVar_list[0] as String?
      val notificationText = pigeonVar_list[1] as String?
      val notificationChannelId = pigeonVar_list[2] as String?
      val notificationChannelName = pigeonVar_list[3] as String?
      val notificationId = pigeonVar_list[4] as Long?
      val foregroundServiceType = pigeonVar_list[5] as ForegroundServiceType?
      return ForegroundServiceConfig(notificationTitle, notificationText, notificationChannelId, notificationChannelName, notificationId, foregroundServiceType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      notificationTitle,
      notificationText,
      notificationChannelId,
      notificationChannelName,
      notificationId,
      foregroundServiceType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ForegroundServiceConfig
    return WorkmanagerApiPigeonUtils.deepEquals(this.notificationTitle, other.notificationTitle) && WorkmanagerApiPigeonUtils.deepEquals(this.notificationText, other.notificationText) && WorkmanagerApiPigeonUtils.deepEquals(this.notificationChannelId, other.notificationChannelId) && WorkmanagerApiPigeonUtils.deepEquals(this.notificationChannelName, other.notificationChannelName) && WorkmanagerApiPigeonUtils.deepEquals(this.notificationId, other.notificationId) && WorkmanagerApiPigeonUtils.deepEquals(this.foregroundServiceType, other.foregroundServiceType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.notificationTitle)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.notificationText)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.notificationChannelId)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.notificationChannelName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.notificationId)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.foregroundServiceType)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Constraints (
  val networkType: NetworkType? = null,
  val requiresBatteryNotLow: Boolean? = null,
  val requiresCharging: Boolean? = null,
  val requiresDeviceIdle: Boolean? = null,
  val requiresStorageNotLow: Boolean? = null,
  /**
   * Content URI triggers that run the work when the observed content URIs
   * change (Android only).
   *
   * Mirrors WorkManager's `Constraints.Builder.addContentUriTrigger`:
   * https://developer.android.com/reference/androidx/work/Constraints.Builder#addContentUriTrigger(android.net.Uri,%20boolean)
   *
   * Requires Android 7.0 (API 24)+; on older Android versions the triggers
   * are ignored. WorkManager also limits how many content-URI-triggered
   * workers can be enqueued at once (default 8, configurable via
   * `Configuration.Builder.setContentUriTriggerWorkersLimit`).
   *
   * Other platforms ignore this field.
   */
  val contentUriTriggers: List<ContentUriTrigger?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Constraints {
      val networkType = pigeonVar_list[0] as NetworkType?
      val requiresBatteryNotLow = pigeonVar_list[1] as Boolean?
      val requiresCharging = pigeonVar_list[2] as Boolean?
      val requiresDeviceIdle = pigeonVar_list[3] as Boolean?
      val requiresStorageNotLow = pigeonVar_list[4] as Boolean?
      val contentUriTriggers = pigeonVar_list[5] as List<ContentUriTrigger?>?
      return Constraints(networkType, requiresBatteryNotLow, requiresCharging, requiresDeviceIdle, requiresStorageNotLow, contentUriTriggers)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      networkType,
      requiresBatteryNotLow,
      requiresCharging,
      requiresDeviceIdle,
      requiresStorageNotLow,
      contentUriTriggers,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Constraints
    return WorkmanagerApiPigeonUtils.deepEquals(this.networkType, other.networkType) && WorkmanagerApiPigeonUtils.deepEquals(this.requiresBatteryNotLow, other.requiresBatteryNotLow) && WorkmanagerApiPigeonUtils.deepEquals(this.requiresCharging, other.requiresCharging) && WorkmanagerApiPigeonUtils.deepEquals(this.requiresDeviceIdle, other.requiresDeviceIdle) && WorkmanagerApiPigeonUtils.deepEquals(this.requiresStorageNotLow, other.requiresStorageNotLow) && WorkmanagerApiPigeonUtils.deepEquals(this.contentUriTriggers, other.contentUriTriggers)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.networkType)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.requiresBatteryNotLow)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.requiresCharging)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.requiresDeviceIdle)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.requiresStorageNotLow)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.contentUriTriggers)
    return result
  }
}

/**
 * A single content URI trigger for Android WorkManager constraints.
 *
 * When [uri] is updated, inserted or deleted by the system or another app,
 * the work associated with the constraint is run.
 *
 * Mirrors WorkManager's `ContentUriTrigger`:
 * https://developer.android.com/reference/androidx/work/ContentUriTrigger
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ContentUriTrigger (
  /**
   * The local `content:` Uri to observe for changes, e.g.
   * `content://media/external/images/media`.
   */
  val uri: String,
  /** Whether changes to any descendant of [uri] also run the work. */
  val triggerForDescendants: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ContentUriTrigger {
      val uri = pigeonVar_list[0] as String
      val triggerForDescendants = pigeonVar_list[1] as Boolean
      return ContentUriTrigger(uri, triggerForDescendants)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      triggerForDescendants,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ContentUriTrigger
    return WorkmanagerApiPigeonUtils.deepEquals(this.uri, other.uri) && WorkmanagerApiPigeonUtils.deepEquals(this.triggerForDescendants, other.triggerForDescendants)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.uri)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.triggerForDescendants)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BackoffPolicyConfig (
  val backoffPolicy: BackoffPolicy? = null,
  val backoffDelayMillis: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BackoffPolicyConfig {
      val backoffPolicy = pigeonVar_list[0] as BackoffPolicy?
      val backoffDelayMillis = pigeonVar_list[1] as Long?
      return BackoffPolicyConfig(backoffPolicy, backoffDelayMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      backoffPolicy,
      backoffDelayMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BackoffPolicyConfig
    return WorkmanagerApiPigeonUtils.deepEquals(this.backoffPolicy, other.backoffPolicy) && WorkmanagerApiPigeonUtils.deepEquals(this.backoffDelayMillis, other.backoffDelayMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.backoffPolicy)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.backoffDelayMillis)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InitializeRequest (
  val callbackHandle: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitializeRequest {
      val callbackHandle = pigeonVar_list[0] as Long
      return InitializeRequest(callbackHandle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      callbackHandle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InitializeRequest
    return WorkmanagerApiPigeonUtils.deepEquals(this.callbackHandle, other.callbackHandle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.callbackHandle)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OneOffTaskRequest (
  val uniqueName: String,
  val taskName: String,
  val inputData: Map<String?, Any?>? = null,
  val initialDelaySeconds: Long? = null,
  val constraints: Constraints? = null,
  val backoffPolicy: BackoffPolicyConfig? = null,
  val tag: String? = null,
  val existingWorkPolicy: ExistingWorkPolicy? = null,
  val outOfQuotaPolicy: OutOfQuotaPolicy? = null,
  /** When set, the worker runs as an Android foreground service. */
  val foregroundServiceConfig: ForegroundServiceConfig? = null,
  /**
   * When true (Android only), the task is scheduled as expedited work.
   *
   * WorkManager runs expedited work with high priority; on Android 12
   * (API 31)+ the system runs it as a WorkManager-managed foreground
   * service and shows a notification to the user. Only meaningful for
   * one-off tasks — periodic tasks cannot be expedited. Other platforms
   * ignore this field.
   */
  val expedited: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OneOffTaskRequest {
      val uniqueName = pigeonVar_list[0] as String
      val taskName = pigeonVar_list[1] as String
      val inputData = pigeonVar_list[2] as Map<String?, Any?>?
      val initialDelaySeconds = pigeonVar_list[3] as Long?
      val constraints = pigeonVar_list[4] as Constraints?
      val backoffPolicy = pigeonVar_list[5] as BackoffPolicyConfig?
      val tag = pigeonVar_list[6] as String?
      val existingWorkPolicy = pigeonVar_list[7] as ExistingWorkPolicy?
      val outOfQuotaPolicy = pigeonVar_list[8] as OutOfQuotaPolicy?
      val foregroundServiceConfig = pigeonVar_list[9] as ForegroundServiceConfig?
      val expedited = pigeonVar_list[10] as Boolean?
      return OneOffTaskRequest(uniqueName, taskName, inputData, initialDelaySeconds, constraints, backoffPolicy, tag, existingWorkPolicy, outOfQuotaPolicy, foregroundServiceConfig, expedited)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uniqueName,
      taskName,
      inputData,
      initialDelaySeconds,
      constraints,
      backoffPolicy,
      tag,
      existingWorkPolicy,
      outOfQuotaPolicy,
      foregroundServiceConfig,
      expedited,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OneOffTaskRequest
    return WorkmanagerApiPigeonUtils.deepEquals(this.uniqueName, other.uniqueName) && WorkmanagerApiPigeonUtils.deepEquals(this.taskName, other.taskName) && WorkmanagerApiPigeonUtils.deepEquals(this.inputData, other.inputData) && WorkmanagerApiPigeonUtils.deepEquals(this.initialDelaySeconds, other.initialDelaySeconds) && WorkmanagerApiPigeonUtils.deepEquals(this.constraints, other.constraints) && WorkmanagerApiPigeonUtils.deepEquals(this.backoffPolicy, other.backoffPolicy) && WorkmanagerApiPigeonUtils.deepEquals(this.tag, other.tag) && WorkmanagerApiPigeonUtils.deepEquals(this.existingWorkPolicy, other.existingWorkPolicy) && WorkmanagerApiPigeonUtils.deepEquals(this.outOfQuotaPolicy, other.outOfQuotaPolicy) && WorkmanagerApiPigeonUtils.deepEquals(this.foregroundServiceConfig, other.foregroundServiceConfig) && WorkmanagerApiPigeonUtils.deepEquals(this.expedited, other.expedited)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.uniqueName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.taskName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.inputData)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.initialDelaySeconds)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.constraints)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.backoffPolicy)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.tag)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.existingWorkPolicy)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.outOfQuotaPolicy)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.foregroundServiceConfig)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.expedited)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeriodicTaskRequest (
  val uniqueName: String,
  val taskName: String,
  val frequencySeconds: Long,
  val flexIntervalSeconds: Long? = null,
  val inputData: Map<String?, Any?>? = null,
  val initialDelaySeconds: Long? = null,
  val constraints: Constraints? = null,
  val backoffPolicy: BackoffPolicyConfig? = null,
  val tag: String? = null,
  val existingWorkPolicy: ExistingPeriodicWorkPolicy? = null,
  /** When set, the worker runs as an Android foreground service. */
  val foregroundServiceConfig: ForegroundServiceConfig? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeriodicTaskRequest {
      val uniqueName = pigeonVar_list[0] as String
      val taskName = pigeonVar_list[1] as String
      val frequencySeconds = pigeonVar_list[2] as Long
      val flexIntervalSeconds = pigeonVar_list[3] as Long?
      val inputData = pigeonVar_list[4] as Map<String?, Any?>?
      val initialDelaySeconds = pigeonVar_list[5] as Long?
      val constraints = pigeonVar_list[6] as Constraints?
      val backoffPolicy = pigeonVar_list[7] as BackoffPolicyConfig?
      val tag = pigeonVar_list[8] as String?
      val existingWorkPolicy = pigeonVar_list[9] as ExistingPeriodicWorkPolicy?
      val foregroundServiceConfig = pigeonVar_list[10] as ForegroundServiceConfig?
      return PeriodicTaskRequest(uniqueName, taskName, frequencySeconds, flexIntervalSeconds, inputData, initialDelaySeconds, constraints, backoffPolicy, tag, existingWorkPolicy, foregroundServiceConfig)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uniqueName,
      taskName,
      frequencySeconds,
      flexIntervalSeconds,
      inputData,
      initialDelaySeconds,
      constraints,
      backoffPolicy,
      tag,
      existingWorkPolicy,
      foregroundServiceConfig,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PeriodicTaskRequest
    return WorkmanagerApiPigeonUtils.deepEquals(this.uniqueName, other.uniqueName) && WorkmanagerApiPigeonUtils.deepEquals(this.taskName, other.taskName) && WorkmanagerApiPigeonUtils.deepEquals(this.frequencySeconds, other.frequencySeconds) && WorkmanagerApiPigeonUtils.deepEquals(this.flexIntervalSeconds, other.flexIntervalSeconds) && WorkmanagerApiPigeonUtils.deepEquals(this.inputData, other.inputData) && WorkmanagerApiPigeonUtils.deepEquals(this.initialDelaySeconds, other.initialDelaySeconds) && WorkmanagerApiPigeonUtils.deepEquals(this.constraints, other.constraints) && WorkmanagerApiPigeonUtils.deepEquals(this.backoffPolicy, other.backoffPolicy) && WorkmanagerApiPigeonUtils.deepEquals(this.tag, other.tag) && WorkmanagerApiPigeonUtils.deepEquals(this.existingWorkPolicy, other.existingWorkPolicy) && WorkmanagerApiPigeonUtils.deepEquals(this.foregroundServiceConfig, other.foregroundServiceConfig)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.uniqueName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.taskName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.frequencySeconds)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.flexIntervalSeconds)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.inputData)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.initialDelaySeconds)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.constraints)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.backoffPolicy)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.tag)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.existingWorkPolicy)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.foregroundServiceConfig)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProcessingTaskRequest (
  val uniqueName: String,
  val taskName: String,
  val inputData: Map<String?, Any?>? = null,
  val initialDelaySeconds: Long? = null,
  val networkType: NetworkType? = null,
  val requiresCharging: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProcessingTaskRequest {
      val uniqueName = pigeonVar_list[0] as String
      val taskName = pigeonVar_list[1] as String
      val inputData = pigeonVar_list[2] as Map<String?, Any?>?
      val initialDelaySeconds = pigeonVar_list[3] as Long?
      val networkType = pigeonVar_list[4] as NetworkType?
      val requiresCharging = pigeonVar_list[5] as Boolean?
      return ProcessingTaskRequest(uniqueName, taskName, inputData, initialDelaySeconds, networkType, requiresCharging)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uniqueName,
      taskName,
      inputData,
      initialDelaySeconds,
      networkType,
      requiresCharging,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProcessingTaskRequest
    return WorkmanagerApiPigeonUtils.deepEquals(this.uniqueName, other.uniqueName) && WorkmanagerApiPigeonUtils.deepEquals(this.taskName, other.taskName) && WorkmanagerApiPigeonUtils.deepEquals(this.inputData, other.inputData) && WorkmanagerApiPigeonUtils.deepEquals(this.initialDelaySeconds, other.initialDelaySeconds) && WorkmanagerApiPigeonUtils.deepEquals(this.networkType, other.networkType) && WorkmanagerApiPigeonUtils.deepEquals(this.requiresCharging, other.requiresCharging)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.uniqueName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.taskName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.inputData)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.initialDelaySeconds)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.networkType)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.requiresCharging)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HealthResearchTaskRequest (
  val uniqueName: String,
  val taskName: String,
  val inputData: Map<String?, Any?>? = null,
  val initialDelaySeconds: Long? = null,
  val networkType: NetworkType? = null,
  val requiresCharging: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HealthResearchTaskRequest {
      val uniqueName = pigeonVar_list[0] as String
      val taskName = pigeonVar_list[1] as String
      val inputData = pigeonVar_list[2] as Map<String?, Any?>?
      val initialDelaySeconds = pigeonVar_list[3] as Long?
      val networkType = pigeonVar_list[4] as NetworkType?
      val requiresCharging = pigeonVar_list[5] as Boolean?
      return HealthResearchTaskRequest(uniqueName, taskName, inputData, initialDelaySeconds, networkType, requiresCharging)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uniqueName,
      taskName,
      inputData,
      initialDelaySeconds,
      networkType,
      requiresCharging,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HealthResearchTaskRequest
    return WorkmanagerApiPigeonUtils.deepEquals(this.uniqueName, other.uniqueName) && WorkmanagerApiPigeonUtils.deepEquals(this.taskName, other.taskName) && WorkmanagerApiPigeonUtils.deepEquals(this.inputData, other.inputData) && WorkmanagerApiPigeonUtils.deepEquals(this.initialDelaySeconds, other.initialDelaySeconds) && WorkmanagerApiPigeonUtils.deepEquals(this.networkType, other.networkType) && WorkmanagerApiPigeonUtils.deepEquals(this.requiresCharging, other.requiresCharging)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.uniqueName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.taskName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.inputData)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.initialDelaySeconds)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.networkType)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.requiresCharging)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ContinuedProcessingTaskRequest (
  val uniqueName: String,
  val taskName: String,
  val title: String? = null,
  val subtitle: String? = null,
  val inputData: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ContinuedProcessingTaskRequest {
      val uniqueName = pigeonVar_list[0] as String
      val taskName = pigeonVar_list[1] as String
      val title = pigeonVar_list[2] as String?
      val subtitle = pigeonVar_list[3] as String?
      val inputData = pigeonVar_list[4] as Map<String?, Any?>?
      return ContinuedProcessingTaskRequest(uniqueName, taskName, title, subtitle, inputData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uniqueName,
      taskName,
      title,
      subtitle,
      inputData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ContinuedProcessingTaskRequest
    return WorkmanagerApiPigeonUtils.deepEquals(this.uniqueName, other.uniqueName) && WorkmanagerApiPigeonUtils.deepEquals(this.taskName, other.taskName) && WorkmanagerApiPigeonUtils.deepEquals(this.title, other.title) && WorkmanagerApiPigeonUtils.deepEquals(this.subtitle, other.subtitle) && WorkmanagerApiPigeonUtils.deepEquals(this.inputData, other.inputData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.uniqueName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.taskName)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.title)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.subtitle)
    result = 31 * result + WorkmanagerApiPigeonUtils.deepHash(this.inputData)
    return result
  }
}
private open class WorkmanagerApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TaskStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NetworkType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BackoffPolicy.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ExistingWorkPolicy.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ExistingPeriodicWorkPolicy.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OutOfQuotaPolicy.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ForegroundServiceType.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ForegroundServiceConfig.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Constraints.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ContentUriTrigger.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BackoffPolicyConfig.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitializeRequest.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OneOffTaskRequest.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeriodicTaskRequest.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProcessingTaskRequest.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HealthResearchTaskRequest.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ContinuedProcessingTaskRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TaskStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NetworkType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is BackoffPolicy -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is ExistingWorkPolicy -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is ExistingPeriodicWorkPolicy -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is OutOfQuotaPolicy -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is ForegroundServiceType -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is ForegroundServiceConfig -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is Constraints -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ContentUriTrigger -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is BackoffPolicyConfig -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is InitializeRequest -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is OneOffTaskRequest -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is PeriodicTaskRequest -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is ProcessingTaskRequest -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is HealthResearchTaskRequest -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is ContinuedProcessingTaskRequest -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WorkmanagerHostApi {
  fun initialize(request: InitializeRequest, callback: (Result<Unit>) -> Unit)
  fun registerOneOffTask(request: OneOffTaskRequest, callback: (Result<Unit>) -> Unit)
  fun registerPeriodicTask(request: PeriodicTaskRequest, callback: (Result<Unit>) -> Unit)
  fun registerProcessingTask(request: ProcessingTaskRequest, callback: (Result<Unit>) -> Unit)
  fun registerHealthResearchTask(request: HealthResearchTaskRequest, callback: (Result<Unit>) -> Unit)
  fun registerContinuedProcessingTask(request: ContinuedProcessingTaskRequest, callback: (Result<Unit>) -> Unit)
  fun cancelByUniqueName(uniqueName: String, callback: (Result<Unit>) -> Unit)
  fun cancelByTag(tag: String, callback: (Result<Unit>) -> Unit)
  fun cancelAll(callback: (Result<Unit>) -> Unit)
  fun isScheduledByUniqueName(uniqueName: String, callback: (Result<Boolean>) -> Unit)
  fun printScheduledTasks(callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by WorkmanagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      WorkmanagerApiPigeonCodec()
    }
    /** Sets up an instance of `WorkmanagerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WorkmanagerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as InitializeRequest
            api.initialize(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerOneOffTask$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as OneOffTaskRequest
            api.registerOneOffTask(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerPeriodicTask$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PeriodicTaskRequest
            api.registerPeriodicTask(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerProcessingTask$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ProcessingTaskRequest
            api.registerProcessingTask(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerHealthResearchTask$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as HealthResearchTaskRequest
            api.registerHealthResearchTask(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerContinuedProcessingTask$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ContinuedProcessingTaskRequest
            api.registerContinuedProcessingTask(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.cancelByUniqueName$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uniqueNameArg = args[0] as String
            api.cancelByUniqueName(uniqueNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.cancelByTag$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            api.cancelByTag(tagArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.cancelAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cancelAll{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.isScheduledByUniqueName$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uniqueNameArg = args[0] as String
            api.isScheduledByUniqueName(uniqueNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.printScheduledTasks$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.printScheduledTasks{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WorkmanagerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WorkmanagerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class WorkmanagerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by WorkmanagerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      WorkmanagerApiPigeonCodec()
    }
  }
  fun backgroundChannelInitialized(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerFlutterApi.backgroundChannelInitialized$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(WorkmanagerApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun executeTask(taskNameArg: String, inputDataArg: Map<String?, Any?>?, callback: (Result<Boolean>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerFlutterApi.executeTask$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskNameArg, inputDataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as Boolean
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(WorkmanagerApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Notifies the Dart callback that a running task was stopped by the
   * platform before it finished (cancelled, timed out, preempted, ...).
   *
   * [stopReason] carries the Android WorkManager stop reason (see
   * [StopReason](https://developer.android.com/reference/androidx/work/StopReason)).
   * It is `0` (unknown) on Android versions before 12 (API 31) and on
   * platforms without an equivalent concept.
   */
  fun onTaskStopped(taskNameArg: String, stopReasonArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerFlutterApi.onTaskStopped$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskNameArg, stopReasonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(WorkmanagerApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
