// // Copyright 2024 The Flutter Workmanager Authors. All rights reserved.
// // Use of this source code is governed by a MIT-style license that can be
// // found in the LICENSE file.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsWorkmanagerApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashWorkmanagerApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsWorkmanagerApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsWorkmanagerApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsWorkmanagerApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsWorkmanagerApi(lhsKey, rhsKey) {
          if deepEqualsWorkmanagerApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsWorkmanagerApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashWorkmanagerApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashWorkmanagerApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashWorkmanagerApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashWorkmanagerApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashWorkmanagerApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashWorkmanagerApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Task status for debugging and monitoring.
enum TaskStatus: Int {
  /// Task has been scheduled
  case scheduled = 0
  /// Task has started execution
  case started = 1
  /// Task completed successfully
  case completed = 2
  /// Task failed
  case failed = 3
  /// Task was cancelled
  case cancelled = 4
  /// Task is being retried
  case retrying = 5
  /// Task was rescheduled for later execution
  case rescheduled = 6
}

/// An enumeration of various network types that can be used as Constraints for work.
///
/// Fully supported on Android.
///
/// On iOS, this enumeration is used to define whether a piece of work requires
/// internet connectivity, by checking for either [NetworkType.connected] or
/// [NetworkType.metered].
enum NetworkType: Int {
  /// Any working network connection is required for this work.
  case connected = 0
  /// A metered network connection is required for this work.
  case metered = 1
  /// Default value. A network is not required for this work.
  case notRequired = 2
  /// A non-roaming network connection is required for this work.
  case notRoaming = 3
  /// An unmetered network connection is required for this work.
  case unmetered = 4
  /// A temporarily unmetered Network. This capability will be set for
  /// networks that are generally metered, but are currently unmetered.
  ///
  /// Android API 30+
  case temporarilyUnmetered = 5
}

/// An enumeration of backoff policies when retrying work.
/// These policies are used when you have a return ListenableWorker.Result.retry() from a worker to determine the correct backoff time.
/// Backoff policies are set in WorkRequest.Builder.setBackoffCriteria(BackoffPolicy, long, TimeUnit) or one of its variants.
enum BackoffPolicy: Int {
  /// Used to indicate that WorkManager should increase the backoff time exponentially
  case exponential = 0
  /// Used to indicate that WorkManager should increase the backoff time linearly
  case linear = 1
}

/// An enumeration of the conflict resolution policies when registering one-off work with the same unique name.
///
/// This policy determines what happens when you register a one-off task with a unique name that already exists.
///
/// See: https://developer.android.com/reference/androidx/work/ExistingWorkPolicy
enum ExistingWorkPolicy: Int {
  /// If there is existing pending (uncompleted) work with the same unique name, append the newly-specified work as a child of all the leaves of that work sequence.
  case append = 0
  /// If there is existing pending (uncompleted) work with the same unique name, do nothing.
  /// The new work request is ignored and the existing work continues unchanged.
  case keep = 1
  /// If there is existing pending (uncompleted) work with the same unique name, cancel and delete it.
  /// The new work request replaces the existing one entirely.
  case replace = 2
  /// If there is existing pending (uncompleted) work with the same unique name, it will be updated with the new specification.
  /// Note: This maps to appendOrReplace in the native implementation.
  case update = 3
}

/// An enumeration of the conflict resolution policies when registering periodic work with the same unique name.
///
/// This policy determines what happens when you register a periodic task with a unique name that already exists.
/// This is especially important during development when you might register the same task multiple times
/// with different frequencies or configurations.
///
/// See: https://developer.android.com/reference/androidx/work/ExistingPeriodicWorkPolicy
enum ExistingPeriodicWorkPolicy: Int {
  /// If there is existing pending (uncompleted) work with the same unique name, do nothing.
  /// The new work request is ignored and the existing work continues unchanged.
  ///
  /// **Warning**: If you previously registered a periodic task with a short frequency
  /// (e.g., 15 minutes) and later register the same task with a longer frequency (e.g., 2 hours),
  /// the task will continue running at the original short frequency. This can cause confusion
  /// during development. Consider using [update] instead.
  case keep = 0
  /// If there is existing pending (uncompleted) work with the same unique name, cancel and delete it.
  /// The new work request replaces the existing one entirely.
  ///
  /// **Deprecated**: Android recommends using [update] instead for less disruptive updates.
  case replace = 1
  /// If there is existing pending (uncompleted) work with the same unique name, it will be updated with the new specification.
  ///
  /// **Recommended** - updates existing work without canceling running workers and preserves original timing.
  /// This is the default policy for periodic tasks to prevent frequency confusion.
  ///
  /// Available since WorkManager 2.8.0.
  case update = 2
}

/// An enumeration of policies that help determine out of quota behavior for expedited jobs.
///
/// Only supported on Android.
enum OutOfQuotaPolicy: Int {
  /// When the app does not have any expedited job quota, the expedited work request will
  /// fallback to a regular work request.
  case runAsNonExpeditedWorkRequest = 0
  /// When the app does not have any expedited job quota, the expedited work request will
  /// we dropped and no work requests are enqueued.
  case dropWorkRequest = 1
}

/// The lifecycle state of a background task as observed by the plugin.
///
/// This is the cross-platform subset of Android WorkManager's
/// `WorkInfo.State` (ENQUEUED/RUNNING/SUCCEEDED/FAILED/CANCELLED/BLOCKED).
/// On Apple platforms it reflects what the plugin itself has persisted from
/// its task-status pipeline, because BGTaskScheduler has no query API.
enum WorkState: Int {
  /// The task is registered and waiting to run (Android ENQUEUED/BLOCKED).
  case scheduled = 0
  /// The task is currently executing.
  case running = 1
  /// The task finished successfully.
  case succeeded = 2
  /// The task failed permanently.
  case failed = 3
  /// The task was cancelled before finishing.
  case cancelled = 4
}

/// Foreground service types supported for Android long-running workers.
///
/// These map to the foreground service types introduced by Android 14
/// (API level 34), when specifying a type became mandatory for apps targeting
/// SDK 34+. See:
/// https://developer.android.com/about/versions/14/changes/fgs-types-required
enum ForegroundServiceType: Int {
  /// Used for long-running data synchronization, uploads and downloads that
  /// are important to the user.
  case dataSync = 0
  /// Used for short, critical work that the user is aware of and that must
  /// complete quickly (a few minutes at most).
  case shortService = 1
}

/// Android-only configuration that promotes a worker to a foreground service
/// while it runs, keeping the process alive for long-running work.
///
/// When provided to [OneOffTaskRequest.foregroundServiceConfig] or
/// [PeriodicTaskRequest.foregroundServiceConfig], the worker calls
/// WorkManager's `setForegroundAsync` as soon as it starts and shows a
/// notification for the whole duration of the task.
///
/// All fields are optional; the platform implementation fills in sane
/// defaults for anything that is not provided.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ForegroundServiceConfig: Hashable {
  /// Title shown in the foreground service notification.
  var notificationTitle: String? = nil
  /// Body text shown in the foreground service notification.
  var notificationText: String? = nil
  /// Id of the notification channel used for the foreground service
  /// notification (Android 8.0+).
  var notificationChannelId: String? = nil
  /// User-visible name of the notification channel.
  var notificationChannelName: String? = nil
  /// Id used for the foreground service notification.
  var notificationId: Int64? = nil
  /// Foreground service type to start with (Android 14+). Defaults to
  /// [ForegroundServiceType.dataSync].
  var foregroundServiceType: ForegroundServiceType? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ForegroundServiceConfig? {
    let notificationTitle: String? = nilOrValue(pigeonVar_list[0])
    let notificationText: String? = nilOrValue(pigeonVar_list[1])
    let notificationChannelId: String? = nilOrValue(pigeonVar_list[2])
    let notificationChannelName: String? = nilOrValue(pigeonVar_list[3])
    let notificationId: Int64? = nilOrValue(pigeonVar_list[4])
    let foregroundServiceType: ForegroundServiceType? = nilOrValue(pigeonVar_list[5])

    return ForegroundServiceConfig(
      notificationTitle: notificationTitle,
      notificationText: notificationText,
      notificationChannelId: notificationChannelId,
      notificationChannelName: notificationChannelName,
      notificationId: notificationId,
      foregroundServiceType: foregroundServiceType
    )
  }
  func toList() -> [Any?] {
    return [
      notificationTitle,
      notificationText,
      notificationChannelId,
      notificationChannelName,
      notificationId,
      foregroundServiceType,
    ]
  }
  static func == (lhs: ForegroundServiceConfig, rhs: ForegroundServiceConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.notificationTitle, rhs.notificationTitle) && deepEqualsWorkmanagerApi(lhs.notificationText, rhs.notificationText) && deepEqualsWorkmanagerApi(lhs.notificationChannelId, rhs.notificationChannelId) && deepEqualsWorkmanagerApi(lhs.notificationChannelName, rhs.notificationChannelName) && deepEqualsWorkmanagerApi(lhs.notificationId, rhs.notificationId) && deepEqualsWorkmanagerApi(lhs.foregroundServiceType, rhs.foregroundServiceType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ForegroundServiceConfig")
    deepHashWorkmanagerApi(value: notificationTitle, hasher: &hasher)
    deepHashWorkmanagerApi(value: notificationText, hasher: &hasher)
    deepHashWorkmanagerApi(value: notificationChannelId, hasher: &hasher)
    deepHashWorkmanagerApi(value: notificationChannelName, hasher: &hasher)
    deepHashWorkmanagerApi(value: notificationId, hasher: &hasher)
    deepHashWorkmanagerApi(value: foregroundServiceType, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Constraints: Hashable {
  var networkType: NetworkType? = nil
  var requiresBatteryNotLow: Bool? = nil
  var requiresCharging: Bool? = nil
  var requiresDeviceIdle: Bool? = nil
  var requiresStorageNotLow: Bool? = nil
  /// Content URI triggers that run the work when the observed content URIs
  /// change (Android only).
  ///
  /// Mirrors WorkManager's `Constraints.Builder.addContentUriTrigger`:
  /// https://developer.android.com/reference/androidx/work/Constraints.Builder#addContentUriTrigger(android.net.Uri,%20boolean)
  ///
  /// Requires Android 7.0 (API 24)+; on older Android versions the triggers
  /// are ignored. WorkManager also limits how many content-URI-triggered
  /// workers can be enqueued at once (default 8, configurable via
  /// `Configuration.Builder.setContentUriTriggerWorkersLimit`).
  ///
  /// Other platforms ignore this field.
  var contentUriTriggers: [ContentUriTrigger?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Constraints? {
    let networkType: NetworkType? = nilOrValue(pigeonVar_list[0])
    let requiresBatteryNotLow: Bool? = nilOrValue(pigeonVar_list[1])
    let requiresCharging: Bool? = nilOrValue(pigeonVar_list[2])
    let requiresDeviceIdle: Bool? = nilOrValue(pigeonVar_list[3])
    let requiresStorageNotLow: Bool? = nilOrValue(pigeonVar_list[4])
    let contentUriTriggers: [ContentUriTrigger?]? = nilOrValue(pigeonVar_list[5])

    return Constraints(
      networkType: networkType,
      requiresBatteryNotLow: requiresBatteryNotLow,
      requiresCharging: requiresCharging,
      requiresDeviceIdle: requiresDeviceIdle,
      requiresStorageNotLow: requiresStorageNotLow,
      contentUriTriggers: contentUriTriggers
    )
  }
  func toList() -> [Any?] {
    return [
      networkType,
      requiresBatteryNotLow,
      requiresCharging,
      requiresDeviceIdle,
      requiresStorageNotLow,
      contentUriTriggers,
    ]
  }
  static func == (lhs: Constraints, rhs: Constraints) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.networkType, rhs.networkType) && deepEqualsWorkmanagerApi(lhs.requiresBatteryNotLow, rhs.requiresBatteryNotLow) && deepEqualsWorkmanagerApi(lhs.requiresCharging, rhs.requiresCharging) && deepEqualsWorkmanagerApi(lhs.requiresDeviceIdle, rhs.requiresDeviceIdle) && deepEqualsWorkmanagerApi(lhs.requiresStorageNotLow, rhs.requiresStorageNotLow) && deepEqualsWorkmanagerApi(lhs.contentUriTriggers, rhs.contentUriTriggers)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Constraints")
    deepHashWorkmanagerApi(value: networkType, hasher: &hasher)
    deepHashWorkmanagerApi(value: requiresBatteryNotLow, hasher: &hasher)
    deepHashWorkmanagerApi(value: requiresCharging, hasher: &hasher)
    deepHashWorkmanagerApi(value: requiresDeviceIdle, hasher: &hasher)
    deepHashWorkmanagerApi(value: requiresStorageNotLow, hasher: &hasher)
    deepHashWorkmanagerApi(value: contentUriTriggers, hasher: &hasher)
  }
}

/// A single content URI trigger for Android WorkManager constraints.
///
/// When [uri] is updated, inserted or deleted by the system or another app,
/// the work associated with the constraint is run.
///
/// Mirrors WorkManager's `ContentUriTrigger`:
/// https://developer.android.com/reference/androidx/work/ContentUriTrigger
///
/// Generated class from Pigeon that represents data sent in messages.
struct ContentUriTrigger: Hashable {
  /// The local `content:` Uri to observe for changes, e.g.
  /// `content://media/external/images/media`.
  var uri: String
  /// Whether changes to any descendant of [uri] also run the work.
  var triggerForDescendants: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ContentUriTrigger? {
    let uri = pigeonVar_list[0] as! String
    let triggerForDescendants = pigeonVar_list[1] as! Bool

    return ContentUriTrigger(
      uri: uri,
      triggerForDescendants: triggerForDescendants
    )
  }
  func toList() -> [Any?] {
    return [
      uri,
      triggerForDescendants,
    ]
  }
  static func == (lhs: ContentUriTrigger, rhs: ContentUriTrigger) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.uri, rhs.uri) && deepEqualsWorkmanagerApi(lhs.triggerForDescendants, rhs.triggerForDescendants)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ContentUriTrigger")
    deepHashWorkmanagerApi(value: uri, hasher: &hasher)
    deepHashWorkmanagerApi(value: triggerForDescendants, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BackoffPolicyConfig: Hashable {
  var backoffPolicy: BackoffPolicy? = nil
  var backoffDelayMillis: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BackoffPolicyConfig? {
    let backoffPolicy: BackoffPolicy? = nilOrValue(pigeonVar_list[0])
    let backoffDelayMillis: Int64? = nilOrValue(pigeonVar_list[1])

    return BackoffPolicyConfig(
      backoffPolicy: backoffPolicy,
      backoffDelayMillis: backoffDelayMillis
    )
  }
  func toList() -> [Any?] {
    return [
      backoffPolicy,
      backoffDelayMillis,
    ]
  }
  static func == (lhs: BackoffPolicyConfig, rhs: BackoffPolicyConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.backoffPolicy, rhs.backoffPolicy) && deepEqualsWorkmanagerApi(lhs.backoffDelayMillis, rhs.backoffDelayMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BackoffPolicyConfig")
    deepHashWorkmanagerApi(value: backoffPolicy, hasher: &hasher)
    deepHashWorkmanagerApi(value: backoffDelayMillis, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct InitializeRequest: Hashable {
  var callbackHandle: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitializeRequest? {
    let callbackHandle = pigeonVar_list[0] as! Int64

    return InitializeRequest(
      callbackHandle: callbackHandle
    )
  }
  func toList() -> [Any?] {
    return [
      callbackHandle
    ]
  }
  static func == (lhs: InitializeRequest, rhs: InitializeRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.callbackHandle, rhs.callbackHandle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("InitializeRequest")
    deepHashWorkmanagerApi(value: callbackHandle, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OneOffTaskRequest: Hashable {
  var uniqueName: String
  var taskName: String
  var inputData: [String?: Any?]? = nil
  var initialDelaySeconds: Int64? = nil
  var constraints: Constraints? = nil
  var backoffPolicy: BackoffPolicyConfig? = nil
  var tag: String? = nil
  var existingWorkPolicy: ExistingWorkPolicy? = nil
  var outOfQuotaPolicy: OutOfQuotaPolicy? = nil
  /// When set, the worker runs as an Android foreground service.
  var foregroundServiceConfig: ForegroundServiceConfig? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OneOffTaskRequest? {
    let uniqueName = pigeonVar_list[0] as! String
    let taskName = pigeonVar_list[1] as! String
    let inputData: [String?: Any?]? = nilOrValue(pigeonVar_list[2])
    let initialDelaySeconds: Int64? = nilOrValue(pigeonVar_list[3])
    let constraints: Constraints? = nilOrValue(pigeonVar_list[4])
    let backoffPolicy: BackoffPolicyConfig? = nilOrValue(pigeonVar_list[5])
    let tag: String? = nilOrValue(pigeonVar_list[6])
    let existingWorkPolicy: ExistingWorkPolicy? = nilOrValue(pigeonVar_list[7])
    let outOfQuotaPolicy: OutOfQuotaPolicy? = nilOrValue(pigeonVar_list[8])
    let foregroundServiceConfig: ForegroundServiceConfig? = nilOrValue(pigeonVar_list[9])

    return OneOffTaskRequest(
      uniqueName: uniqueName,
      taskName: taskName,
      inputData: inputData,
      initialDelaySeconds: initialDelaySeconds,
      constraints: constraints,
      backoffPolicy: backoffPolicy,
      tag: tag,
      existingWorkPolicy: existingWorkPolicy,
      outOfQuotaPolicy: outOfQuotaPolicy,
      foregroundServiceConfig: foregroundServiceConfig
    )
  }
  func toList() -> [Any?] {
    return [
      uniqueName,
      taskName,
      inputData,
      initialDelaySeconds,
      constraints,
      backoffPolicy,
      tag,
      existingWorkPolicy,
      outOfQuotaPolicy,
      foregroundServiceConfig,
    ]
  }
  static func == (lhs: OneOffTaskRequest, rhs: OneOffTaskRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.uniqueName, rhs.uniqueName) && deepEqualsWorkmanagerApi(lhs.taskName, rhs.taskName) && deepEqualsWorkmanagerApi(lhs.inputData, rhs.inputData) && deepEqualsWorkmanagerApi(lhs.initialDelaySeconds, rhs.initialDelaySeconds) && deepEqualsWorkmanagerApi(lhs.constraints, rhs.constraints) && deepEqualsWorkmanagerApi(lhs.backoffPolicy, rhs.backoffPolicy) && deepEqualsWorkmanagerApi(lhs.tag, rhs.tag) && deepEqualsWorkmanagerApi(lhs.existingWorkPolicy, rhs.existingWorkPolicy) && deepEqualsWorkmanagerApi(lhs.outOfQuotaPolicy, rhs.outOfQuotaPolicy) && deepEqualsWorkmanagerApi(lhs.foregroundServiceConfig, rhs.foregroundServiceConfig)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OneOffTaskRequest")
    deepHashWorkmanagerApi(value: uniqueName, hasher: &hasher)
    deepHashWorkmanagerApi(value: taskName, hasher: &hasher)
    deepHashWorkmanagerApi(value: inputData, hasher: &hasher)
    deepHashWorkmanagerApi(value: initialDelaySeconds, hasher: &hasher)
    deepHashWorkmanagerApi(value: constraints, hasher: &hasher)
    deepHashWorkmanagerApi(value: backoffPolicy, hasher: &hasher)
    deepHashWorkmanagerApi(value: tag, hasher: &hasher)
    deepHashWorkmanagerApi(value: existingWorkPolicy, hasher: &hasher)
    deepHashWorkmanagerApi(value: outOfQuotaPolicy, hasher: &hasher)
    deepHashWorkmanagerApi(value: foregroundServiceConfig, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PeriodicTaskRequest: Hashable {
  var uniqueName: String
  var taskName: String
  var frequencySeconds: Int64
  var flexIntervalSeconds: Int64? = nil
  var inputData: [String?: Any?]? = nil
  var initialDelaySeconds: Int64? = nil
  var constraints: Constraints? = nil
  var backoffPolicy: BackoffPolicyConfig? = nil
  var tag: String? = nil
  var existingWorkPolicy: ExistingPeriodicWorkPolicy? = nil
  /// When set, the worker runs as an Android foreground service.
  var foregroundServiceConfig: ForegroundServiceConfig? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PeriodicTaskRequest? {
    let uniqueName = pigeonVar_list[0] as! String
    let taskName = pigeonVar_list[1] as! String
    let frequencySeconds = pigeonVar_list[2] as! Int64
    let flexIntervalSeconds: Int64? = nilOrValue(pigeonVar_list[3])
    let inputData: [String?: Any?]? = nilOrValue(pigeonVar_list[4])
    let initialDelaySeconds: Int64? = nilOrValue(pigeonVar_list[5])
    let constraints: Constraints? = nilOrValue(pigeonVar_list[6])
    let backoffPolicy: BackoffPolicyConfig? = nilOrValue(pigeonVar_list[7])
    let tag: String? = nilOrValue(pigeonVar_list[8])
    let existingWorkPolicy: ExistingPeriodicWorkPolicy? = nilOrValue(pigeonVar_list[9])
    let foregroundServiceConfig: ForegroundServiceConfig? = nilOrValue(pigeonVar_list[10])

    return PeriodicTaskRequest(
      uniqueName: uniqueName,
      taskName: taskName,
      frequencySeconds: frequencySeconds,
      flexIntervalSeconds: flexIntervalSeconds,
      inputData: inputData,
      initialDelaySeconds: initialDelaySeconds,
      constraints: constraints,
      backoffPolicy: backoffPolicy,
      tag: tag,
      existingWorkPolicy: existingWorkPolicy,
      foregroundServiceConfig: foregroundServiceConfig
    )
  }
  func toList() -> [Any?] {
    return [
      uniqueName,
      taskName,
      frequencySeconds,
      flexIntervalSeconds,
      inputData,
      initialDelaySeconds,
      constraints,
      backoffPolicy,
      tag,
      existingWorkPolicy,
      foregroundServiceConfig,
    ]
  }
  static func == (lhs: PeriodicTaskRequest, rhs: PeriodicTaskRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.uniqueName, rhs.uniqueName) && deepEqualsWorkmanagerApi(lhs.taskName, rhs.taskName) && deepEqualsWorkmanagerApi(lhs.frequencySeconds, rhs.frequencySeconds) && deepEqualsWorkmanagerApi(lhs.flexIntervalSeconds, rhs.flexIntervalSeconds) && deepEqualsWorkmanagerApi(lhs.inputData, rhs.inputData) && deepEqualsWorkmanagerApi(lhs.initialDelaySeconds, rhs.initialDelaySeconds) && deepEqualsWorkmanagerApi(lhs.constraints, rhs.constraints) && deepEqualsWorkmanagerApi(lhs.backoffPolicy, rhs.backoffPolicy) && deepEqualsWorkmanagerApi(lhs.tag, rhs.tag) && deepEqualsWorkmanagerApi(lhs.existingWorkPolicy, rhs.existingWorkPolicy) && deepEqualsWorkmanagerApi(lhs.foregroundServiceConfig, rhs.foregroundServiceConfig)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PeriodicTaskRequest")
    deepHashWorkmanagerApi(value: uniqueName, hasher: &hasher)
    deepHashWorkmanagerApi(value: taskName, hasher: &hasher)
    deepHashWorkmanagerApi(value: frequencySeconds, hasher: &hasher)
    deepHashWorkmanagerApi(value: flexIntervalSeconds, hasher: &hasher)
    deepHashWorkmanagerApi(value: inputData, hasher: &hasher)
    deepHashWorkmanagerApi(value: initialDelaySeconds, hasher: &hasher)
    deepHashWorkmanagerApi(value: constraints, hasher: &hasher)
    deepHashWorkmanagerApi(value: backoffPolicy, hasher: &hasher)
    deepHashWorkmanagerApi(value: tag, hasher: &hasher)
    deepHashWorkmanagerApi(value: existingWorkPolicy, hasher: &hasher)
    deepHashWorkmanagerApi(value: foregroundServiceConfig, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProcessingTaskRequest: Hashable {
  var uniqueName: String
  var taskName: String
  var inputData: [String?: Any?]? = nil
  var initialDelaySeconds: Int64? = nil
  var networkType: NetworkType? = nil
  var requiresCharging: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProcessingTaskRequest? {
    let uniqueName = pigeonVar_list[0] as! String
    let taskName = pigeonVar_list[1] as! String
    let inputData: [String?: Any?]? = nilOrValue(pigeonVar_list[2])
    let initialDelaySeconds: Int64? = nilOrValue(pigeonVar_list[3])
    let networkType: NetworkType? = nilOrValue(pigeonVar_list[4])
    let requiresCharging: Bool? = nilOrValue(pigeonVar_list[5])

    return ProcessingTaskRequest(
      uniqueName: uniqueName,
      taskName: taskName,
      inputData: inputData,
      initialDelaySeconds: initialDelaySeconds,
      networkType: networkType,
      requiresCharging: requiresCharging
    )
  }
  func toList() -> [Any?] {
    return [
      uniqueName,
      taskName,
      inputData,
      initialDelaySeconds,
      networkType,
      requiresCharging,
    ]
  }
  static func == (lhs: ProcessingTaskRequest, rhs: ProcessingTaskRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.uniqueName, rhs.uniqueName) && deepEqualsWorkmanagerApi(lhs.taskName, rhs.taskName) && deepEqualsWorkmanagerApi(lhs.inputData, rhs.inputData) && deepEqualsWorkmanagerApi(lhs.initialDelaySeconds, rhs.initialDelaySeconds) && deepEqualsWorkmanagerApi(lhs.networkType, rhs.networkType) && deepEqualsWorkmanagerApi(lhs.requiresCharging, rhs.requiresCharging)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProcessingTaskRequest")
    deepHashWorkmanagerApi(value: uniqueName, hasher: &hasher)
    deepHashWorkmanagerApi(value: taskName, hasher: &hasher)
    deepHashWorkmanagerApi(value: inputData, hasher: &hasher)
    deepHashWorkmanagerApi(value: initialDelaySeconds, hasher: &hasher)
    deepHashWorkmanagerApi(value: networkType, hasher: &hasher)
    deepHashWorkmanagerApi(value: requiresCharging, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HealthResearchTaskRequest: Hashable {
  var uniqueName: String
  var taskName: String
  var inputData: [String?: Any?]? = nil
  var initialDelaySeconds: Int64? = nil
  var networkType: NetworkType? = nil
  var requiresCharging: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthResearchTaskRequest? {
    let uniqueName = pigeonVar_list[0] as! String
    let taskName = pigeonVar_list[1] as! String
    let inputData: [String?: Any?]? = nilOrValue(pigeonVar_list[2])
    let initialDelaySeconds: Int64? = nilOrValue(pigeonVar_list[3])
    let networkType: NetworkType? = nilOrValue(pigeonVar_list[4])
    let requiresCharging: Bool? = nilOrValue(pigeonVar_list[5])

    return HealthResearchTaskRequest(
      uniqueName: uniqueName,
      taskName: taskName,
      inputData: inputData,
      initialDelaySeconds: initialDelaySeconds,
      networkType: networkType,
      requiresCharging: requiresCharging
    )
  }
  func toList() -> [Any?] {
    return [
      uniqueName,
      taskName,
      inputData,
      initialDelaySeconds,
      networkType,
      requiresCharging,
    ]
  }
  static func == (lhs: HealthResearchTaskRequest, rhs: HealthResearchTaskRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.uniqueName, rhs.uniqueName) && deepEqualsWorkmanagerApi(lhs.taskName, rhs.taskName) && deepEqualsWorkmanagerApi(lhs.inputData, rhs.inputData) && deepEqualsWorkmanagerApi(lhs.initialDelaySeconds, rhs.initialDelaySeconds) && deepEqualsWorkmanagerApi(lhs.networkType, rhs.networkType) && deepEqualsWorkmanagerApi(lhs.requiresCharging, rhs.requiresCharging)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HealthResearchTaskRequest")
    deepHashWorkmanagerApi(value: uniqueName, hasher: &hasher)
    deepHashWorkmanagerApi(value: taskName, hasher: &hasher)
    deepHashWorkmanagerApi(value: inputData, hasher: &hasher)
    deepHashWorkmanagerApi(value: initialDelaySeconds, hasher: &hasher)
    deepHashWorkmanagerApi(value: networkType, hasher: &hasher)
    deepHashWorkmanagerApi(value: requiresCharging, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ContinuedProcessingTaskRequest: Hashable {
  var uniqueName: String
  var taskName: String
  var title: String? = nil
  var subtitle: String? = nil
  var inputData: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ContinuedProcessingTaskRequest? {
    let uniqueName = pigeonVar_list[0] as! String
    let taskName = pigeonVar_list[1] as! String
    let title: String? = nilOrValue(pigeonVar_list[2])
    let subtitle: String? = nilOrValue(pigeonVar_list[3])
    let inputData: [String?: Any?]? = nilOrValue(pigeonVar_list[4])

    return ContinuedProcessingTaskRequest(
      uniqueName: uniqueName,
      taskName: taskName,
      title: title,
      subtitle: subtitle,
      inputData: inputData
    )
  }
  func toList() -> [Any?] {
    return [
      uniqueName,
      taskName,
      title,
      subtitle,
      inputData,
    ]
  }
  static func == (lhs: ContinuedProcessingTaskRequest, rhs: ContinuedProcessingTaskRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.uniqueName, rhs.uniqueName) && deepEqualsWorkmanagerApi(lhs.taskName, rhs.taskName) && deepEqualsWorkmanagerApi(lhs.title, rhs.title) && deepEqualsWorkmanagerApi(lhs.subtitle, rhs.subtitle) && deepEqualsWorkmanagerApi(lhs.inputData, rhs.inputData)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ContinuedProcessingTaskRequest")
    deepHashWorkmanagerApi(value: uniqueName, hasher: &hasher)
    deepHashWorkmanagerApi(value: taskName, hasher: &hasher)
    deepHashWorkmanagerApi(value: title, hasher: &hasher)
    deepHashWorkmanagerApi(value: subtitle, hasher: &hasher)
    deepHashWorkmanagerApi(value: inputData, hasher: &hasher)
  }
}

/// Snapshot of the current state of a background task, as served by the
/// native platform. This is the transport type for [WorkmanagerHostApi.getWorkInfoByUniqueName];
/// the public, platform-agnostic model is `WorkInfo`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WorkInfoData: Hashable {
  /// The unique name the task was registered with.
  var uniqueName: String
  /// The task's current state.
  var state: WorkState
  /// True when the task was registered as a periodic task.
  var isPeriodic: Bool
  /// The task name the work was registered with, when the platform exposes it.
  var taskName: String? = nil
  /// Tags the work was registered with (Android only; empty elsewhere).
  var tags: [String?]? = nil
  /// When the plugin last observed the task finish (succeeded, failed or was
  /// cancelled), as epoch milliseconds, when the platform exposes it.
  /// Android WorkManager has no finish timestamp, so this is null there.
  var lastFinishedAtMillis: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WorkInfoData? {
    let uniqueName = pigeonVar_list[0] as! String
    let state = pigeonVar_list[1] as! WorkState
    let isPeriodic = pigeonVar_list[2] as! Bool
    let taskName: String? = nilOrValue(pigeonVar_list[3])
    let tags: [String?]? = nilOrValue(pigeonVar_list[4])
    let lastFinishedAtMillis: Int64? = nilOrValue(pigeonVar_list[5])

    return WorkInfoData(
      uniqueName: uniqueName,
      state: state,
      isPeriodic: isPeriodic,
      taskName: taskName,
      tags: tags,
      lastFinishedAtMillis: lastFinishedAtMillis
    )
  }
  func toList() -> [Any?] {
    return [
      uniqueName,
      state,
      isPeriodic,
      taskName,
      tags,
      lastFinishedAtMillis,
    ]
  }
  static func == (lhs: WorkInfoData, rhs: WorkInfoData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWorkmanagerApi(lhs.uniqueName, rhs.uniqueName) && deepEqualsWorkmanagerApi(lhs.state, rhs.state) && deepEqualsWorkmanagerApi(lhs.isPeriodic, rhs.isPeriodic) && deepEqualsWorkmanagerApi(lhs.taskName, rhs.taskName) && deepEqualsWorkmanagerApi(lhs.tags, rhs.tags) && deepEqualsWorkmanagerApi(lhs.lastFinishedAtMillis, rhs.lastFinishedAtMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WorkInfoData")
    deepHashWorkmanagerApi(value: uniqueName, hasher: &hasher)
    deepHashWorkmanagerApi(value: state, hasher: &hasher)
    deepHashWorkmanagerApi(value: isPeriodic, hasher: &hasher)
    deepHashWorkmanagerApi(value: taskName, hasher: &hasher)
    deepHashWorkmanagerApi(value: tags, hasher: &hasher)
    deepHashWorkmanagerApi(value: lastFinishedAtMillis, hasher: &hasher)
  }
}

private class WorkmanagerApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TaskStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NetworkType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BackoffPolicy(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ExistingWorkPolicy(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ExistingPeriodicWorkPolicy(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OutOfQuotaPolicy(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WorkState(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ForegroundServiceType(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      return ForegroundServiceConfig.fromList(self.readValue() as! [Any?])
    case 138:
      return Constraints.fromList(self.readValue() as! [Any?])
    case 139:
      return ContentUriTrigger.fromList(self.readValue() as! [Any?])
    case 140:
      return BackoffPolicyConfig.fromList(self.readValue() as! [Any?])
    case 141:
      return InitializeRequest.fromList(self.readValue() as! [Any?])
    case 142:
      return OneOffTaskRequest.fromList(self.readValue() as! [Any?])
    case 143:
      return PeriodicTaskRequest.fromList(self.readValue() as! [Any?])
    case 144:
      return ProcessingTaskRequest.fromList(self.readValue() as! [Any?])
    case 145:
      return HealthResearchTaskRequest.fromList(self.readValue() as! [Any?])
    case 146:
      return ContinuedProcessingTaskRequest.fromList(self.readValue() as! [Any?])
    case 147:
      return WorkInfoData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class WorkmanagerApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TaskStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NetworkType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? BackoffPolicy {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? ExistingWorkPolicy {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? ExistingPeriodicWorkPolicy {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? OutOfQuotaPolicy {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? WorkState {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? ForegroundServiceType {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? ForegroundServiceConfig {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? Constraints {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ContentUriTrigger {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? BackoffPolicyConfig {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? InitializeRequest {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? OneOffTaskRequest {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? PeriodicTaskRequest {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? ProcessingTaskRequest {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? HealthResearchTaskRequest {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? ContinuedProcessingTaskRequest {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? WorkInfoData {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class WorkmanagerApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WorkmanagerApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WorkmanagerApiPigeonCodecWriter(data: data)
  }
}

class WorkmanagerApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WorkmanagerApiPigeonCodec(readerWriter: WorkmanagerApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WorkmanagerHostApi {
  func initialize(request: InitializeRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func registerOneOffTask(request: OneOffTaskRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func registerPeriodicTask(request: PeriodicTaskRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func registerProcessingTask(request: ProcessingTaskRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func registerHealthResearchTask(request: HealthResearchTaskRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func registerContinuedProcessingTask(request: ContinuedProcessingTaskRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelByUniqueName(uniqueName: String, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelByTag(tag: String, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelAll(completion: @escaping (Result<Void, Error>) -> Void)
  func isScheduledByUniqueName(uniqueName: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func printScheduledTasks(completion: @escaping (Result<String, Error>) -> Void)
  /// Returns the current state of the task registered under [uniqueName], or
  /// null when the platform has no record of it.
  func getWorkInfoByUniqueName(uniqueName: String, completion: @escaping (Result<WorkInfoData?, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WorkmanagerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { WorkmanagerApiPigeonCodec.shared }
  /// Sets up an instance of `WorkmanagerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WorkmanagerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! InitializeRequest
        api.initialize(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let registerOneOffTaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerOneOffTask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerOneOffTaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! OneOffTaskRequest
        api.registerOneOffTask(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerOneOffTaskChannel.setMessageHandler(nil)
    }
    let registerPeriodicTaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerPeriodicTask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerPeriodicTaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PeriodicTaskRequest
        api.registerPeriodicTask(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerPeriodicTaskChannel.setMessageHandler(nil)
    }
    let registerProcessingTaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerProcessingTask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerProcessingTaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ProcessingTaskRequest
        api.registerProcessingTask(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerProcessingTaskChannel.setMessageHandler(nil)
    }
    let registerHealthResearchTaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerHealthResearchTask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerHealthResearchTaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! HealthResearchTaskRequest
        api.registerHealthResearchTask(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerHealthResearchTaskChannel.setMessageHandler(nil)
    }
    let registerContinuedProcessingTaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerContinuedProcessingTask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerContinuedProcessingTaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ContinuedProcessingTaskRequest
        api.registerContinuedProcessingTask(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerContinuedProcessingTaskChannel.setMessageHandler(nil)
    }
    let cancelByUniqueNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.cancelByUniqueName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelByUniqueNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uniqueNameArg = args[0] as! String
        api.cancelByUniqueName(uniqueName: uniqueNameArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelByUniqueNameChannel.setMessageHandler(nil)
    }
    let cancelByTagChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.cancelByTag\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelByTagChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        api.cancelByTag(tag: tagArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelByTagChannel.setMessageHandler(nil)
    }
    let cancelAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.cancelAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAllChannel.setMessageHandler { _, reply in
        api.cancelAll { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelAllChannel.setMessageHandler(nil)
    }
    let isScheduledByUniqueNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.isScheduledByUniqueName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isScheduledByUniqueNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uniqueNameArg = args[0] as! String
        api.isScheduledByUniqueName(uniqueName: uniqueNameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isScheduledByUniqueNameChannel.setMessageHandler(nil)
    }
    let printScheduledTasksChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.printScheduledTasks\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printScheduledTasksChannel.setMessageHandler { _, reply in
        api.printScheduledTasks { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printScheduledTasksChannel.setMessageHandler(nil)
    }
    /// Returns the current state of the task registered under [uniqueName], or
    /// null when the platform has no record of it.
    let getWorkInfoByUniqueNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.getWorkInfoByUniqueName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getWorkInfoByUniqueNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uniqueNameArg = args[0] as! String
        api.getWorkInfoByUniqueName(uniqueName: uniqueNameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getWorkInfoByUniqueNameChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WorkmanagerFlutterApiProtocol {
  func backgroundChannelInitialized(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func executeTask(taskName taskNameArg: String, inputData inputDataArg: [String?: Any?]?, completion: @escaping (Result<Bool, PigeonError>) -> Void)
  /// Notifies the Dart callback that a running task was stopped by the
  /// platform before it finished (cancelled, timed out, preempted, ...).
  ///
  /// [stopReason] carries the Android WorkManager stop reason (see
  /// [StopReason](https://developer.android.com/reference/androidx/work/StopReason)).
  /// It is `0` (unknown) on Android versions before 12 (API 31) and on
  /// platforms without an equivalent concept.
  func onTaskStopped(taskName taskNameArg: String, stopReason stopReasonArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WorkmanagerFlutterApi: WorkmanagerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: WorkmanagerApiPigeonCodec {
    return WorkmanagerApiPigeonCodec.shared
  }
  func backgroundChannelInitialized(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerFlutterApi.backgroundChannelInitialized\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func executeTask(taskName taskNameArg: String, inputData inputDataArg: [String?: Any?]?, completion: @escaping (Result<Bool, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerFlutterApi.executeTask\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([taskNameArg, inputDataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
  /// Notifies the Dart callback that a running task was stopped by the
  /// platform before it finished (cancelled, timed out, preempted, ...).
  ///
  /// [stopReason] carries the Android WorkManager stop reason (see
  /// [StopReason](https://developer.android.com/reference/androidx/work/StopReason)).
  /// It is `0` (unknown) on Android versions before 12 (API 31) and on
  /// platforms without an equivalent concept.
  func onTaskStopped(taskName taskNameArg: String, stopReason stopReasonArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerFlutterApi.onTaskStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([taskNameArg, stopReasonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
