// // Copyright 2024 The Flutter Workmanager Authors. All rights reserved.
// // Use of this source code is governed by a MIT-style license that can be
// // found in the LICENSE file.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Task status for debugging and monitoring.
enum TaskStatus {
  /// Task has been scheduled
  scheduled,
  /// Task has started execution
  started,
  /// Task completed successfully
  completed,
  /// Task failed
  failed,
  /// Task was cancelled
  cancelled,
  /// Task is being retried
  retrying,
  /// Task was rescheduled for later execution
  rescheduled,
}

/// An enumeration of various network types that can be used as Constraints for work.
///
/// Fully supported on Android.
///
/// On iOS, this enumeration is used to define whether a piece of work requires
/// internet connectivity, by checking for either [NetworkType.connected] or
/// [NetworkType.metered].
enum NetworkType {
  /// Any working network connection is required for this work.
  connected,
  /// A metered network connection is required for this work.
  metered,
  /// Default value. A network is not required for this work.
  notRequired,
  /// A non-roaming network connection is required for this work.
  notRoaming,
  /// An unmetered network connection is required for this work.
  unmetered,
  /// A temporarily unmetered Network. This capability will be set for
  /// networks that are generally metered, but are currently unmetered.
  ///
  /// Android API 30+
  temporarilyUnmetered,
}

/// An enumeration of backoff policies when retrying work.
/// These policies are used when you have a return ListenableWorker.Result.retry() from a worker to determine the correct backoff time.
/// Backoff policies are set in WorkRequest.Builder.setBackoffCriteria(BackoffPolicy, long, TimeUnit) or one of its variants.
enum BackoffPolicy {
  /// Used to indicate that WorkManager should increase the backoff time exponentially
  exponential,
  /// Used to indicate that WorkManager should increase the backoff time linearly
  linear,
}

/// An enumeration of the conflict resolution policies when registering one-off work with the same unique name.
///
/// This policy determines what happens when you register a one-off task with a unique name that already exists.
///
/// See: https://developer.android.com/reference/androidx/work/ExistingWorkPolicy
enum ExistingWorkPolicy {
  /// If there is existing pending (uncompleted) work with the same unique name, append the newly-specified work as a child of all the leaves of that work sequence.
  append,
  /// If there is existing pending (uncompleted) work with the same unique name, do nothing.
  /// The new work request is ignored and the existing work continues unchanged.
  keep,
  /// If there is existing pending (uncompleted) work with the same unique name, cancel and delete it.
  /// The new work request replaces the existing one entirely.
  replace,
  /// If there is existing pending (uncompleted) work with the same unique name, it will be updated with the new specification.
  /// Note: This maps to appendOrReplace in the native implementation.
  update,
}

/// An enumeration of the conflict resolution policies when registering periodic work with the same unique name.
///
/// This policy determines what happens when you register a periodic task with a unique name that already exists.
/// This is especially important during development when you might register the same task multiple times
/// with different frequencies or configurations.
///
/// See: https://developer.android.com/reference/androidx/work/ExistingPeriodicWorkPolicy
enum ExistingPeriodicWorkPolicy {
  /// If there is existing pending (uncompleted) work with the same unique name, do nothing.
  /// The new work request is ignored and the existing work continues unchanged.
  ///
  /// **Warning**: If you previously registered a periodic task with a short frequency
  /// (e.g., 15 minutes) and later register the same task with a longer frequency (e.g., 2 hours),
  /// the task will continue running at the original short frequency. This can cause confusion
  /// during development. Consider using [update] instead.
  keep,
  /// If there is existing pending (uncompleted) work with the same unique name, cancel and delete it.
  /// The new work request replaces the existing one entirely.
  ///
  /// **Deprecated**: Android recommends using [update] instead for less disruptive updates.
  replace,
  /// If there is existing pending (uncompleted) work with the same unique name, it will be updated with the new specification.
  ///
  /// **Recommended** - updates existing work without canceling running workers and preserves original timing.
  /// This is the default policy for periodic tasks to prevent frequency confusion.
  ///
  /// Available since WorkManager 2.8.0.
  update,
}

/// An enumeration of policies that help determine out of quota behavior for expedited jobs.
///
/// Only supported on Android.
enum OutOfQuotaPolicy {
  /// When the app does not have any expedited job quota, the expedited work request will
  /// fallback to a regular work request.
  runAsNonExpeditedWorkRequest,
  /// When the app does not have any expedited job quota, the expedited work request will
  /// we dropped and no work requests are enqueued.
  dropWorkRequest,
}

/// Foreground service types supported for Android long-running workers.
///
/// These map to the foreground service types introduced by Android 14
/// (API level 34), when specifying a type became mandatory for apps targeting
/// SDK 34+. See:
/// https://developer.android.com/about/versions/14/changes/fgs-types-required
enum ForegroundServiceType {
  /// Used for long-running data synchronization, uploads and downloads that
  /// are important to the user.
  dataSync,
  /// Used for short, critical work that the user is aware of and that must
  /// complete quickly (a few minutes at most).
  shortService,
}

/// Result of a background task execution.
///
/// Replaces the previous `bool` return value of the task handler. Maps to
/// platform-specific semantics:
/// - [success]: Android `Result.success()`, iOS `UIBackgroundFetchResult.newData`.
/// - [retry]: Android `Result.retry()` (transient failure, backoff applies).
///   iOS has no automatic retry — the task finishes as `.failed` and you can
///   re-schedule it yourself.
/// - [failure]: Android `Result.failure()` (permanent failure, dependent work
///   stops and the task is not retried). iOS `UIBackgroundFetchResult.failed`.
enum BackgroundTaskResult {
  /// The task completed successfully.
  success,
  /// The task failed transiently and should be retried (Android only).
  retry,
  /// The task failed permanently and must not be retried.
  failure,
}

/// Android-only configuration that promotes a worker to a foreground service
/// while it runs, keeping the process alive for long-running work.
///
/// When provided to [OneOffTaskRequest.foregroundServiceConfig] or
/// [PeriodicTaskRequest.foregroundServiceConfig], the worker calls
/// WorkManager's `setForegroundAsync` as soon as it starts and shows a
/// notification for the whole duration of the task.
///
/// All fields are optional; the platform implementation fills in sane
/// defaults for anything that is not provided.
class ForegroundServiceConfig {
  ForegroundServiceConfig({
    this.notificationTitle,
    this.notificationText,
    this.notificationChannelId,
    this.notificationChannelName,
    this.notificationId,
    this.foregroundServiceType,
  });

  /// Title shown in the foreground service notification.
  String? notificationTitle;

  /// Body text shown in the foreground service notification.
  String? notificationText;

  /// Id of the notification channel used for the foreground service
  /// notification (Android 8.0+).
  String? notificationChannelId;

  /// User-visible name of the notification channel.
  String? notificationChannelName;

  /// Id used for the foreground service notification.
  int? notificationId;

  /// Foreground service type to start with (Android 14+). Defaults to
  /// [ForegroundServiceType.dataSync].
  ForegroundServiceType? foregroundServiceType;

  List<Object?> _toList() {
    return <Object?>[
      notificationTitle,
      notificationText,
      notificationChannelId,
      notificationChannelName,
      notificationId,
      foregroundServiceType,
    ];
  }

  Object encode() {
    return _toList();  }

  static ForegroundServiceConfig decode(Object result) {
    result as List<Object?>;
    return ForegroundServiceConfig(
      notificationTitle: result[0] as String?,
      notificationText: result[1] as String?,
      notificationChannelId: result[2] as String?,
      notificationChannelName: result[3] as String?,
      notificationId: result[4] as int?,
      foregroundServiceType: result[5] as ForegroundServiceType?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ForegroundServiceConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(notificationTitle, other.notificationTitle) && _deepEquals(notificationText, other.notificationText) && _deepEquals(notificationChannelId, other.notificationChannelId) && _deepEquals(notificationChannelName, other.notificationChannelName) && _deepEquals(notificationId, other.notificationId) && _deepEquals(foregroundServiceType, other.foregroundServiceType);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class Constraints {
  Constraints({
    this.networkType,
    this.requiresBatteryNotLow,
    this.requiresCharging,
    this.requiresDeviceIdle,
    this.requiresStorageNotLow,
    this.contentUriTriggers,
  });

  NetworkType? networkType;

  bool? requiresBatteryNotLow;

  bool? requiresCharging;

  bool? requiresDeviceIdle;

  bool? requiresStorageNotLow;

  /// Content URI triggers that run the work when the observed content URIs
  /// change (Android only).
  ///
  /// Mirrors WorkManager's `Constraints.Builder.addContentUriTrigger`:
  /// https://developer.android.com/reference/androidx/work/Constraints.Builder#addContentUriTrigger(android.net.Uri,%20boolean)
  ///
  /// Requires Android 7.0 (API 24)+; on older Android versions the triggers
  /// are ignored. WorkManager also limits how many content-URI-triggered
  /// workers can be enqueued at once (default 8, configurable via
  /// `Configuration.Builder.setContentUriTriggerWorkersLimit`).
  ///
  /// Other platforms ignore this field.
  List<ContentUriTrigger?>? contentUriTriggers;

  List<Object?> _toList() {
    return <Object?>[
      networkType,
      requiresBatteryNotLow,
      requiresCharging,
      requiresDeviceIdle,
      requiresStorageNotLow,
      contentUriTriggers,
    ];
  }

  Object encode() {
    return _toList();  }

  static Constraints decode(Object result) {
    result as List<Object?>;
    return Constraints(
      networkType: result[0] as NetworkType?,
      requiresBatteryNotLow: result[1] as bool?,
      requiresCharging: result[2] as bool?,
      requiresDeviceIdle: result[3] as bool?,
      requiresStorageNotLow: result[4] as bool?,
      contentUriTriggers: (result[5] as List<Object?>?)?.cast<ContentUriTrigger?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Constraints || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(networkType, other.networkType) && _deepEquals(requiresBatteryNotLow, other.requiresBatteryNotLow) && _deepEquals(requiresCharging, other.requiresCharging) && _deepEquals(requiresDeviceIdle, other.requiresDeviceIdle) && _deepEquals(requiresStorageNotLow, other.requiresStorageNotLow) && _deepEquals(contentUriTriggers, other.contentUriTriggers);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A single content URI trigger for Android WorkManager constraints.
///
/// When [uri] is updated, inserted or deleted by the system or another app,
/// the work associated with the constraint is run.
///
/// Mirrors WorkManager's `ContentUriTrigger`:
/// https://developer.android.com/reference/androidx/work/ContentUriTrigger
class ContentUriTrigger {
  ContentUriTrigger({
    required this.uri,
    required this.triggerForDescendants,
  });

  /// The local `content:` Uri to observe for changes, e.g.
  /// `content://media/external/images/media`.
  String uri;

  /// Whether changes to any descendant of [uri] also run the work.
  bool triggerForDescendants;

  List<Object?> _toList() {
    return <Object?>[
      uri,
      triggerForDescendants,
    ];
  }

  Object encode() {
    return _toList();  }

  static ContentUriTrigger decode(Object result) {
    result as List<Object?>;
    return ContentUriTrigger(
      uri: result[0]! as String,
      triggerForDescendants: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ContentUriTrigger || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) && _deepEquals(triggerForDescendants, other.triggerForDescendants);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class BackoffPolicyConfig {
  BackoffPolicyConfig({
    this.backoffPolicy,
    this.backoffDelayMillis,
  });

  BackoffPolicy? backoffPolicy;

  int? backoffDelayMillis;

  List<Object?> _toList() {
    return <Object?>[
      backoffPolicy,
      backoffDelayMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static BackoffPolicyConfig decode(Object result) {
    result as List<Object?>;
    return BackoffPolicyConfig(
      backoffPolicy: result[0] as BackoffPolicy?,
      backoffDelayMillis: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BackoffPolicyConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(backoffPolicy, other.backoffPolicy) && _deepEquals(backoffDelayMillis, other.backoffDelayMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class InitializeRequest {
  InitializeRequest({
    required this.callbackHandle,
  });

  int callbackHandle;

  List<Object?> _toList() {
    return <Object?>[
      callbackHandle,
    ];
  }

  Object encode() {
    return _toList();  }

  static InitializeRequest decode(Object result) {
    result as List<Object?>;
    return InitializeRequest(
      callbackHandle: result[0]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InitializeRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(callbackHandle, other.callbackHandle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class OneOffTaskRequest {
  OneOffTaskRequest({
    required this.uniqueName,
    required this.taskName,
    this.inputData,
    this.initialDelaySeconds,
    this.constraints,
    this.backoffPolicy,
    this.tag,
    this.existingWorkPolicy,
    this.outOfQuotaPolicy,
    this.foregroundServiceConfig,
  });

  String uniqueName;

  String taskName;

  Map<String?, Object?>? inputData;

  int? initialDelaySeconds;

  Constraints? constraints;

  BackoffPolicyConfig? backoffPolicy;

  String? tag;

  ExistingWorkPolicy? existingWorkPolicy;

  OutOfQuotaPolicy? outOfQuotaPolicy;

  /// When set, the worker runs as an Android foreground service.
  ForegroundServiceConfig? foregroundServiceConfig;

  List<Object?> _toList() {
    return <Object?>[
      uniqueName,
      taskName,
      inputData,
      initialDelaySeconds,
      constraints,
      backoffPolicy,
      tag,
      existingWorkPolicy,
      outOfQuotaPolicy,
      foregroundServiceConfig,
    ];
  }

  Object encode() {
    return _toList();  }

  static OneOffTaskRequest decode(Object result) {
    result as List<Object?>;
    return OneOffTaskRequest(
      uniqueName: result[0]! as String,
      taskName: result[1]! as String,
      inputData: (result[2] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
      initialDelaySeconds: result[3] as int?,
      constraints: result[4] as Constraints?,
      backoffPolicy: result[5] as BackoffPolicyConfig?,
      tag: result[6] as String?,
      existingWorkPolicy: result[7] as ExistingWorkPolicy?,
      outOfQuotaPolicy: result[8] as OutOfQuotaPolicy?,
      foregroundServiceConfig: result[9] as ForegroundServiceConfig?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OneOffTaskRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uniqueName, other.uniqueName) && _deepEquals(taskName, other.taskName) && _deepEquals(inputData, other.inputData) && _deepEquals(initialDelaySeconds, other.initialDelaySeconds) && _deepEquals(constraints, other.constraints) && _deepEquals(backoffPolicy, other.backoffPolicy) && _deepEquals(tag, other.tag) && _deepEquals(existingWorkPolicy, other.existingWorkPolicy) && _deepEquals(outOfQuotaPolicy, other.outOfQuotaPolicy) && _deepEquals(foregroundServiceConfig, other.foregroundServiceConfig);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PeriodicTaskRequest {
  PeriodicTaskRequest({
    required this.uniqueName,
    required this.taskName,
    required this.frequencySeconds,
    this.flexIntervalSeconds,
    this.inputData,
    this.initialDelaySeconds,
    this.constraints,
    this.backoffPolicy,
    this.tag,
    this.existingWorkPolicy,
    this.foregroundServiceConfig,
  });

  String uniqueName;

  String taskName;

  int frequencySeconds;

  int? flexIntervalSeconds;

  Map<String?, Object?>? inputData;

  int? initialDelaySeconds;

  Constraints? constraints;

  BackoffPolicyConfig? backoffPolicy;

  String? tag;

  ExistingPeriodicWorkPolicy? existingWorkPolicy;

  /// When set, the worker runs as an Android foreground service.
  ForegroundServiceConfig? foregroundServiceConfig;

  List<Object?> _toList() {
    return <Object?>[
      uniqueName,
      taskName,
      frequencySeconds,
      flexIntervalSeconds,
      inputData,
      initialDelaySeconds,
      constraints,
      backoffPolicy,
      tag,
      existingWorkPolicy,
      foregroundServiceConfig,
    ];
  }

  Object encode() {
    return _toList();  }

  static PeriodicTaskRequest decode(Object result) {
    result as List<Object?>;
    return PeriodicTaskRequest(
      uniqueName: result[0]! as String,
      taskName: result[1]! as String,
      frequencySeconds: result[2]! as int,
      flexIntervalSeconds: result[3] as int?,
      inputData: (result[4] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
      initialDelaySeconds: result[5] as int?,
      constraints: result[6] as Constraints?,
      backoffPolicy: result[7] as BackoffPolicyConfig?,
      tag: result[8] as String?,
      existingWorkPolicy: result[9] as ExistingPeriodicWorkPolicy?,
      foregroundServiceConfig: result[10] as ForegroundServiceConfig?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PeriodicTaskRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uniqueName, other.uniqueName) && _deepEquals(taskName, other.taskName) && _deepEquals(frequencySeconds, other.frequencySeconds) && _deepEquals(flexIntervalSeconds, other.flexIntervalSeconds) && _deepEquals(inputData, other.inputData) && _deepEquals(initialDelaySeconds, other.initialDelaySeconds) && _deepEquals(constraints, other.constraints) && _deepEquals(backoffPolicy, other.backoffPolicy) && _deepEquals(tag, other.tag) && _deepEquals(existingWorkPolicy, other.existingWorkPolicy) && _deepEquals(foregroundServiceConfig, other.foregroundServiceConfig);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ProcessingTaskRequest {
  ProcessingTaskRequest({
    required this.uniqueName,
    required this.taskName,
    this.inputData,
    this.initialDelaySeconds,
    this.networkType,
    this.requiresCharging,
  });

  String uniqueName;

  String taskName;

  Map<String?, Object?>? inputData;

  int? initialDelaySeconds;

  NetworkType? networkType;

  bool? requiresCharging;

  List<Object?> _toList() {
    return <Object?>[
      uniqueName,
      taskName,
      inputData,
      initialDelaySeconds,
      networkType,
      requiresCharging,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProcessingTaskRequest decode(Object result) {
    result as List<Object?>;
    return ProcessingTaskRequest(
      uniqueName: result[0]! as String,
      taskName: result[1]! as String,
      inputData: (result[2] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
      initialDelaySeconds: result[3] as int?,
      networkType: result[4] as NetworkType?,
      requiresCharging: result[5] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProcessingTaskRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uniqueName, other.uniqueName) && _deepEquals(taskName, other.taskName) && _deepEquals(inputData, other.inputData) && _deepEquals(initialDelaySeconds, other.initialDelaySeconds) && _deepEquals(networkType, other.networkType) && _deepEquals(requiresCharging, other.requiresCharging);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class HealthResearchTaskRequest {
  HealthResearchTaskRequest({
    required this.uniqueName,
    required this.taskName,
    this.inputData,
    this.initialDelaySeconds,
    this.networkType,
    this.requiresCharging,
  });

  String uniqueName;

  String taskName;

  Map<String?, Object?>? inputData;

  int? initialDelaySeconds;

  NetworkType? networkType;

  bool? requiresCharging;

  List<Object?> _toList() {
    return <Object?>[
      uniqueName,
      taskName,
      inputData,
      initialDelaySeconds,
      networkType,
      requiresCharging,
    ];
  }

  Object encode() {
    return _toList();  }

  static HealthResearchTaskRequest decode(Object result) {
    result as List<Object?>;
    return HealthResearchTaskRequest(
      uniqueName: result[0]! as String,
      taskName: result[1]! as String,
      inputData: (result[2] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
      initialDelaySeconds: result[3] as int?,
      networkType: result[4] as NetworkType?,
      requiresCharging: result[5] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HealthResearchTaskRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uniqueName, other.uniqueName) && _deepEquals(taskName, other.taskName) && _deepEquals(inputData, other.inputData) && _deepEquals(initialDelaySeconds, other.initialDelaySeconds) && _deepEquals(networkType, other.networkType) && _deepEquals(requiresCharging, other.requiresCharging);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ContinuedProcessingTaskRequest {
  ContinuedProcessingTaskRequest({
    required this.uniqueName,
    required this.taskName,
    this.title,
    this.subtitle,
    this.inputData,
  });

  String uniqueName;

  String taskName;

  String? title;

  String? subtitle;

  Map<String?, Object?>? inputData;

  List<Object?> _toList() {
    return <Object?>[
      uniqueName,
      taskName,
      title,
      subtitle,
      inputData,
    ];
  }

  Object encode() {
    return _toList();  }

  static ContinuedProcessingTaskRequest decode(Object result) {
    result as List<Object?>;
    return ContinuedProcessingTaskRequest(
      uniqueName: result[0]! as String,
      taskName: result[1]! as String,
      title: result[2] as String?,
      subtitle: result[3] as String?,
      inputData: (result[4] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ContinuedProcessingTaskRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uniqueName, other.uniqueName) && _deepEquals(taskName, other.taskName) && _deepEquals(title, other.title) && _deepEquals(subtitle, other.subtitle) && _deepEquals(inputData, other.inputData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TaskStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is NetworkType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is BackoffPolicy) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is ExistingWorkPolicy) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is ExistingPeriodicWorkPolicy) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is OutOfQuotaPolicy) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is ForegroundServiceType) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is BackgroundTaskResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is ForegroundServiceConfig) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is Constraints) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is ContentUriTrigger) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is BackoffPolicyConfig) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is InitializeRequest) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is OneOffTaskRequest) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is PeriodicTaskRequest) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is ProcessingTaskRequest) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is HealthResearchTaskRequest) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is ContinuedProcessingTaskRequest) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : TaskStatus.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : NetworkType.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : BackoffPolicy.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : ExistingWorkPolicy.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : ExistingPeriodicWorkPolicy.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : OutOfQuotaPolicy.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : ForegroundServiceType.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : BackgroundTaskResult.values[value];
      case 137:
        return ForegroundServiceConfig.decode(readValue(buffer)!);
      case 138:
        return Constraints.decode(readValue(buffer)!);
      case 139:
        return ContentUriTrigger.decode(readValue(buffer)!);
      case 140:
        return BackoffPolicyConfig.decode(readValue(buffer)!);
      case 141:
        return InitializeRequest.decode(readValue(buffer)!);
      case 142:
        return OneOffTaskRequest.decode(readValue(buffer)!);
      case 143:
        return PeriodicTaskRequest.decode(readValue(buffer)!);
      case 144:
        return ProcessingTaskRequest.decode(readValue(buffer)!);
      case 145:
        return HealthResearchTaskRequest.decode(readValue(buffer)!);
      case 146:
        return ContinuedProcessingTaskRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class WorkmanagerHostApi {
  /// Constructor for [WorkmanagerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WorkmanagerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(InitializeRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> registerOneOffTask(OneOffTaskRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerOneOffTask$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> registerPeriodicTask(PeriodicTaskRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerPeriodicTask$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> registerProcessingTask(ProcessingTaskRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerProcessingTask$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> registerHealthResearchTask(HealthResearchTaskRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerHealthResearchTask$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> registerContinuedProcessingTask(ContinuedProcessingTaskRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.registerContinuedProcessingTask$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cancelByUniqueName(String uniqueName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.cancelByUniqueName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[uniqueName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cancelByTag(String tag) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.cancelByTag$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[tag]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cancelAll() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.cancelAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> isScheduledByUniqueName(String uniqueName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.isScheduledByUniqueName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[uniqueName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<String> printScheduledTasks() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerHostApi.printScheduledTasks$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }
}

abstract class WorkmanagerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<void> backgroundChannelInitialized();

  Future<BackgroundTaskResult> executeTask(String taskName, Map<String?, Object?>? inputData);

  /// Notifies the Dart callback that a running task was stopped by the
  /// platform before it finished (cancelled, timed out, preempted, ...).
  ///
  /// [stopReason] carries the Android WorkManager stop reason (see
  /// [StopReason](https://developer.android.com/reference/androidx/work/StopReason)).
  /// It is `0` (unknown) on Android versions before 12 (API 31) and on
  /// platforms without an equivalent concept.
  Future<void> onTaskStopped(String taskName, int stopReason);

  static void setUp(WorkmanagerFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerFlutterApi.backgroundChannelInitialized$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            await api.backgroundChannelInitialized();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerFlutterApi.executeTask$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_taskName = args[0]! as String;
          final Map<String?, Object?>? arg_inputData = (args[1] as Map<Object?, Object?>?)?.cast<String?, Object?>();
          try {
            final BackgroundTaskResult output = await api.executeTask(arg_taskName, arg_inputData);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.workmanager_platform_interface.WorkmanagerFlutterApi.onTaskStopped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_taskName = args[0]! as String;
          final int arg_stopReason = args[1]! as int;
          try {
            await api.onTaskStopped(arg_taskName, arg_stopReason);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
