name: analysis
on: pull_request

jobs:
  package-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [workmanager, workmanager_platform_interface, workmanager_android, workmanager_ios]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - uses: bluefireteam/melos-action@v3
      
      # Only run dart-package-analyzer on the main workmanager package
      # The platform-specific packages are not meant to be published individually
      - uses: axel-op/dart-package-analyzer@v3
        if: matrix.package == 'workmanager'
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: ${{ matrix.package }}/
      
      # For other packages, run standard Flutter analysis
      - name: Analyze package
        if: matrix.package != 'workmanager'
        run: |
          cd ${{ matrix.package }}
          flutter analyze
          dart pub publish --dry-run