name: analysis
on: pull_request

jobs:
  package-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [workmanager, workmanager_platform_interface, workmanager_android, workmanager_ios]
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/dart-package-analyzer@v3
        with:
          # Required:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: ${{ matrix.package }}/